### ISSUE TITLE
Corrección de errores

### ISSUE THREAD

**Issue by FI-RA** [FI-RA/Tarea8_ProgWebII#1]
Se discutirá en torno a errores de código o su correspondiente optimización en base al proyecto Tarea8_ProgWebII.

**Comment by hgonzalezs** [comment]
Me parece un problema de seguridad que la contraseña y el usuario estén sin encriptar, sería una mejora muy buena.

**Comment by FI-RA** [comment]
Excelente, se trabajará en el desarrollar la encriptación.
